CREATE EXTERNAL TABLE IF NOT EXISTS event
(
    reqId    string         COMMENT 'AuctionID, Example: BBD6E1CD8C4B40CB8A624BBC7AFE07D',
    ts       bigint         COMMENT 'Client timestamp(millisecond), Example: 1567479919643',
    fit      int            COMMENT 'First Install Time, unixTimestamp, Example: 1567479919',
    flt      int            COMMENT 'First Launch Time, unixTimestamp, Example: 1567479919',
    zo       int            COMMENT 'ZoneOffset in minutes. <br>Beijing zo=480, Example: 480',
    tz       string         COMMENT 'localTimeZone.name,<br>TimeZone.getDefault().getID(), Example: Asia/Shanghai︎',
    session  string         COMMENT 'SessionID(UUID), Generated when sdk init, Example: BBD6E1CD-8C4B-40CB-8A62-4BBC7AFE07D6',
    uid      string         COMMENT 'Unique user ID generated by SDK, Example: BBD6E1CD-8C4B-40CB-8A62-4BBC7AFE07D6',
    did      string         COMMENT 'DeviceID, @see dtype, Example: BBD6E1CD-8C4B-40CB-8A62-4BBC7AFE07D6',
    dtype    TINYINT        COMMENT 'DeviceID Type, 1:IDFA, 2:GAID, 3:FBID, 4:HUAWEIID, Example: 1',
    lang     string         COMMENT 'Language Code, Example: en-US',
    langname string         COMMENT 'Language Name, Example: English',
    jb       TINYINT        COMMENT 'jailbreak status, 0:normal,1:breaked, Example: 1',
    bundle   string         COMMENT 'Host App PackageName, Example: com.xxx.xxx',
    make     string         COMMENT 'Phone Make, Example: samsung',
    brand    string         COMMENT 'Phone Brand, Example: samsung',
    model    string         COMMENT 'Phone Model, Example: iPhone10,3',
    osv      string         COMMENT 'OS Version, Example: 12.1',
    build    string         COMMENT 'build number, Android: ro.build.display.id, Example: 16A366',
    appv     string         COMMENT 'App Version Name, Example: 1.0',
    width    int            COMMENT 'width of placement or screen, Example: 1028',
    height   int            COMMENT 'height of placement or screen, Example: 2094',
    contype  int            COMMENT 'connectiontype, Example: 4',
    carrier  string         COMMENT 'NetworkOperatorName with mccmnc, Example: 46002China Mobile',
    lip      string         COMMENT 'Local ip, Example: 192.168.1.101',
    lcountry string         COMMENT 'Locale.getCountry, Example: CN',
    fm       int            COMMENT 'Free hard disk space, unit M, Example: 17799',
    battery  int            COMMENT 'Remaining battery percentage, Example: 52',
    btch     TINYINT        COMMENT 'whether charging, 0:否,1:是, Example: 1',
    lowp     TINYINT        COMMENT 'Whether low battery mode, 0:否,1:是, Example: 0',
    cnl      string         COMMENT 'Android Channel',
    gender   TINYINT        COMMENT '0:unknown,1:male,2:female, Example: 1',
    age      TINYINT        COMMENT 'Age year, Example: 26',
    cdid     string         COMMENT 'Custom DeviceID',
    atts     TINYINT        COMMENT 'The status value for app tracking authorization.<br>0 = not determined,<br>1 = restricted,<br>2 = denied,<br>3 = authorized, Example: 2',
    events   ARRAY<Map<String,String>>
) PARTITIONED BY (
    y string,
    m string,
    d string,
    h string
    )
    ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
        WITH
        SERDEPROPERTIES ('serialization.format' = '1', 'ignore.malformed.json' = 'true')
    LOCATION 's3://[(${s3Bucket})]/[(${tableDataPath})]/event/'
    TBLPROPERTIES ('has_encrypted_data' = 'false')
;
