
CREATE EXTERNAL TABLE IF NOT EXISTS lr
(
    ts          bigint,
    fit         int,
    flt         int,
    zo          int,
    session     string,
    uid         string,
    did         string,
    dtype       int,
    lang        string,
    langname    string,
    jb          int,
    bundle      string,
    make        string,
    brand       string,
    model       string,
    osv         string,
    appv        string,
    width       int,
    height      int,
    contype     int,
    carrier     string,
    lip         string,
    lcountry    string,
    fm          int,
    battery     int,
    btch        int,
    ip          string,
    country     string,
    region      string,
    city        string,
    plat        int,
    sdkv        string,
    apiv        int,
    reqId       string,
    serverTs    bigint,
    ua          string,
    abt         int,
    dcenter     int,
    snode       int,
    publisherId int,
    pubAppId    int,
    type        int,
    pid         int,
    mid         int,
    iid         int,
    act         int,
    scene       int,
    status      int,
    msg         string,
    price       decimal(20, 8),
    adType      int,
    bid         int,

    init        int,
    wfReq       int,
    wfFil       int,
    insReq      int,
    insFil      int,
    vdStart     int,
    vdEnd       int,
    calledShow  int,
    readyTrue   int,
    readyFalse  int,
    click       int,
    impr        int,
    bidReq      int,
    bidRes      int,
    bidResPrice decimal(20, 8),
    bidWin      int,
    bidWinPrice decimal(20, 8)
) PARTITIONED BY (
    y string,
    m string,
    d string,
    h string
    )
    ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
        WITH
        SERDEPROPERTIES ('serialization.format' = '1', 'ignore.malformed.json' = 'true')
    LOCATION 's3://[(${s3Bucket})]/[(${tableDataPath})]/lr/'
    TBLPROPERTIES ('has_encrypted_data' = 'false')
;